<?php
// $Id$

/**
 * @file
 * Provides a datepicker for the "Authored on" date field found on node forms.
 */

/**
 * Implementation of hook_help().
 */
function date_popup_authored_help($section) {
  switch ($section) {
    case 'admin/help#date_popup_authored':
      // Return a line-break version of the module README
      $readme = file_get_contents(dirname(__FILE__) . '/README.txt');
      $readme = filter_filter('process', 2, NULL, $readme);
      $readme = filter_filter('process', 1, NULL, $readme);

      return $readme;
  }
}

/**
 * Implementation of hook_form_alter().
 */
function date_popup_authored_form_alter(&$form, $form_state, $form_id) {
  if (strstr($form_id, '_node_form') !== FALSE) {
    $form['author']['date']['#type'] = 'date_popup';
    unset($form['author']['date']['#maxlength']);
    unset($form['author']['date']['#description']);
    
    // We need to modify date popup's data during submit
    // @see http://drupal.org/node/847854
    $form['#submit'][] = 'date_popup_authored_node_form_submit';
  }
}

/**
 * Submits the node data with the proper post date.
 *
 * @see http://drupal.org/node/847854
 */
function date_popup_authored_node_form_submit($form, &$form_state) {

  // Determine user's timezone and convert the date to the authored field format.
  $timezone = date_default_timezone_name();
  $time     = date_make_date($form_state['values']['date'], $timezone, DATE_DATETIME);

  $form_state['values']['date'] = date_format_date($time, 'custom', 'Y-m-d H:i:s O');
}